language: node_js

node_js:
  - lts/*

script:
  - npm run build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: PERSONAL_ACESS_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  local-dir: dist
  on:
    branch: master
